apiVersion: v2
name: argocd-apps-of-apps
description: ArgoCD Applications of Applications Chart
version: 0.1.0

# Define the available variables for this chart
# Use the default values if the values are not supplied
# Use the .Values.argocd.* to access the variables in the templates
values:
  argocd:
    name: argocd-apps-of-apps
    namespace: argocd
    replicaCount: 1
    image:
      repository: argoproj/argocd
      tag: latest
      pullPolicy: IfNotPresent
    server:
      url: http://argocd-server.argocd.svc:80
    app:
      name: apps-of-apps
      source:
        repoURL: https://github.com/billybackmanh/argocd.git
        path: apps
        targetRevision: HEAD
        syncPolicy:
          automated:
            prune: true
            selfHeal: true

# Define the resources that this chart creates
# The resources are created using the templates in the templates directory
resources:
  - resources/argocd-apps-of-apps.yaml

# Define the templates that are used to create the resources
# Use the {{ .Values.argocd.* }} to access the variables in the templates
templates:
  - resources/argocd-apps-of-apps.yaml

# Define the dependencies of this chart
# These are the charts that are required to run this chart
dependencies:
  - name: argocd-server
    version: 0.1.0
    repository: https://kubernetes-charts.storage.googleapis.com
