apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  selector:
    matchLabels:
      app: argocd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-app