enabled: true
admin_group: "Admin"
namespace: confluent-operator
confluent_namespaces: 
  - default
  - cambio-cdr-qa
  - integrations-qa

confluent-for-kubernetes:
  namespaced: false
  serviceAccount:
    create: false
    name: "confluent-for-kubernetes-sa"
  licenseSecretRef: confluent-license # TODO: Change back to license.secretRef
  # license:
  #   secretRef: confluent-license
