apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gsd
  namespace: argocd
spec:
  project: default
  source:
    image: getting-started 
    repoURL: https://github.com/billybackmanh/getting-started.git
    values: |
      server:
        ingress:
          enabled: true
          hosts:
          - host: gsd.minikube.local
            paths: /
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default