apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: getting-started
  namespace: argocd
spec:
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: getting-started
    repoURL: https://github.com/billybackmanh/getting-started.git
    targetRevision: main