apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
     hosts: frontend.minikube.local
      paths:
      - path: /
        backend:
          serviceName: vault
          servicePort: 8200