apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.23.0
    helm:
      releaseName: vault
    values: |
      server:
        ingress:
          enabled: true
          hosts:
          - host: frontend.minikube.local
            paths: /
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default